let arrayRelojes =[
    {id:1, marca: "FESTINA", nombre:"SPECIAL EDITIONS F20524/1", color: "Azul", material: "ACERO INOX", precio: 500, categoria:"HOMBRE", img:'./img/productos/f20524_1.png',cantidad: 1},
    {id:2, marca: "FESTINA", nombre:"CHRONO BIKE F20543/1", color: "Plata", material: "ACERO INOX", precio: 500, categoria: "HOMBRE", img:'./img/productos/f20543_1.png', cantidad: 1},
    {id:3, marca: "FESTINA", nombre:"CHRONO BIKE F20544/4 ",color: "Azul", material: "CAUCHO", precio: 500, categoria: "HOMBRE", img:'./img/productos/f20544_4.png', cantidad: 1},
    {id:4, marca: "FESTINA", nombre:"PRESTIGE F20493/2 ", color: "Negro", material: "ACERO INOX", precio: 500, categoria: "HOMBRE", img:'./img/productos/f20493_2.png', cantidad: 1},
    {id:5, marca: "FESTINA", nombre:"CHRONO BIKE 2021 F20544/3", color: "Verde", material: "CAUCHO", precio: 500, categoria: "HOMBRE", img:'./img/productos/f20544_3.png', cantidad: 1},
    {id:6, marca: "FESTINA", nombre:"CHRONO SPORT F20448/3", color: "Azul", material: "ACERO INOX", precio: 500, categoria: "HOMBRE", img:'./img/productos/f20448_3.png', cantidad: 1},
    {id:7, marca: "FESTINA", nombre:"CHRONO SPORT F20541/3", color: "Verde", material: "ACERO", precio: 500, categoria: "HOMBRE", img:'./img/productos/f20541_3.png',cantidad: 1},
    {id:8, marca: "FESTINA", nombre:"CHRONO SPORT F20450/6", color: "Azul", material: "CAUCHO", precio: 500, categoria: "HOMBRE", img:'./img/productos/f20450_6.png', cantidad: 1},
    {id:9, marca: "FESTINA", nombre:"TIMELESS F20271/1", color: "Blanco", material: "CAUCHO", precio: 500, categoria: "HOMBRE", img:'./img/productos/f20271_1.png', cantidad: 1},
    {id:10, marca:"FESTINA", nombre:"ORIGINALS F20368/1", color: "Negro", material:  "CAUCHO", precio: 500, categoria: "HOMBRE", img:'./img/productos/f20368_1.png', cantidad: 1},
    {id:11, marca:"FESTINA", nombre:"ORIGINALS F20377/1", color: "Plata", material: "PIEL", precio: 500, categoria: "HOMBRE", img:'./img/productos/f20377_1.png', cantidad: 1},
    {id:12, marca:"FESTINA", nombre:"AUTOMATIC F20480/4", color: "Negro", material: "ACERO INOX", precio: 500, categoria: "HOMBRE", img:'./img/productos/f20480_4.png', cantidad: 1},
    {id:13, marca:"FESTINA", nombre:"BOYFRIEND F20399/1", color:"Plata", material:"ACERO", precio: 500,  categoria:"MUJER", img:"./img/productos/f20399_1.png", cantidad: 1},
    {id:14, marca:"FESTINA", nombre:"BOYFRIEND F20397/2", color:"Azul", material:"ACERO", precio: 500,  categoria:"MUJER", img:"./img/productos/f20397_2.png", cantidad: 1},
    {id:15, marca:"FESTINA", nombre:"BOYFRIEND F20397/1", color:"Nacar", material:"ACERO INOX", precio: 500,  categoria:"MUJER", img:"./img/productos/f20397_1.png", cantidad: 1},
    {id:16, marca:"FESTINA", nombre:"MADEMOISELLE F20333/1", color:"Plata", material:"ACERO INOX", precio: 500, categoria:"MUJER", img:"./img/productos/f20333_1.png", cantidad: 1},
    {id:17, marca:"FESTINA", nombre:"BOYFRIEND F16721/2", color:"Rosa", material:"ACERO",precio: 500, categoria:"MUJER", img:"./img/productos/f16721_2.png", cantidad: 1},
    {id:18, marca:"FESTINA", nombre:"MADEMOISELLE F20386/2", color:"Champan", material:"ACERO INOX", precio: 500, categoria:"MUJER", img:"./img/productos/f20386_2.png", cantidad: 1},
    {id:19, marca:"FESTINA", nombre:"MADEMOISELLE F16868/2", color:"Plata", material:"ACERO", precio: 500, categoria:"MUJER", img:"./img/productos/f16868_2.png", cantidad: 1},
    {id:20, marca:"FESTINA", nombre:"MADEMOISELLE F20331/2", color:"Azul", material:"ACERO INOX", precio: 500, categoria:"MUJER", img:"./img/productos/f20331_2.png", cantidad: 1},
    {id:21, marca:"FESTINA", nombre:"BOYFRIEND F20373/1", color:"Rosa", material:"PIEL", precio: 500, categoria:"MUJER", img:"./img/productos/f20373_1.png", cantidad: 1},
]


